### PR TITLE
Fix/data

### PR DESCRIPTION
**Pull request by romajain1**
There is a function for checking missing values in the data. But, for python 3.6+, throws error. 
`Traceback (most recent call last):
  File "offline_training.py", line 133, in <module>
    m = loop.LocalOutlierProbability(real_data, extent=2, n_neighbors=20, use_numba=True, progress_bar=True).fit()
  File "lib/python3.10/site-packages/PyNomaly/loop.py", line 751, in fit
    if self.data is not None and self.Validate._missing_values(
  File "/lib/python3.10/site-packages/PyNomaly/loop.py", line 238, in _missing_values
    if np.any(np.isnan(obj.data)):
  File "/lib/python3.10/site-packages/pandas/core/generic.py", line 2102, in __array_ufunc__
    return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
  File "/lib/python3.10/site-packages/pandas/core/arraylike.py", line 404, in array_ufunc
    result = mgr.apply(getattr(ufunc, method))
  File "/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = b.apply(f, **kwargs)
  File "/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 366, in apply
    result = func(self.values, **kwargs)
  File "/lib/python3.10/site-packages/pandas/core/arrays/categorical.py", line 1665, in __array_ufunc__
    raise TypeError(
TypeError: Object with dtype category cannot perform the numpy op isnan`

### CODE REVIEW

**Comment by IroNEDR** [comment]
@vc1492a I have just finished up our new test-pipeline. It makes sense to merge the PR https://github.com/vc1492a/PyNomaly/pull/58 first so we can have automated testing active on this PR before merge

**Comment by vc1492a** [comment]
> @vc1492a I have just finished up our new test-pipeline. It makes sense to merge the PR #58 first so we can have automated testing active on this PR before merge

Thanks @IroNEDR. I have approved #58 and it's ready for a merge.

**Comment by IroNEDR** [comment]
@romajain1 can you give us more details on how you encountered this error? We have a [test pipeline setup ](
https://github.com/vc1492a/PyNomaly/actions/runs/10907895312/job/30272629566) for Python 3.6 running on Ubntu and a unit test that actually evaluates the userwarning [raised by the missing values](https://github.com/vc1492a/PyNomaly/blob/main/tests/test_loop.py#L547) function as well as several others tests that also execute this method under the hood without problems.

Can you provide us with the following information:
- Python version
- Your OS
- Pandas Version
- Numpy Version

That would be helpful so we can better evaluate the changes

**Comment by vc1492a** [comment]
Closing due to inactivity.

**Pull request closed without merging**
