### PR TITLE
Changes to distance matrix measure to improve speed

### PR DESCRIPTION
**Pull request by nghiadanh26**
Updated my code to loop.py, including a function name "distance_dn" to calculate distance_matrix and "distance_point_dn" calculate distance from a point to training data.
Added some time.time() functions to estimate time for my code.

### CODE REVIEW

**Comment by vc1492a** [comment]
Relates to [this issue](https://github.com/vc1492a/PyNomaly/issues/38#issuecomment-634543733).

**Comment by vc1492a** [comment]
@nghiadanh26 thanks for opening this PR, I took a look at the changes. 

While it does run significantly faster, I am hesitant to pursue this further at the moment as it seems your changes alter the results a non-negligible amount versus the results from the original paper.

The below plot shows the LoOP values calculated for a set of values from the original paper. 

Screen Shot 2020-06-06 at 6 01 43 PM 

The file `examples/multiple_gaussian_2d.py` can be used to create a plot very similar to that provided in the original work, which can be used as a check to ensure that the PyNomaly implementation is as close to the original work as possible. When using the current PyNomaly code, we get the following result: 

Screen Shot 2020-06-06 at 6 01 53 PM

And using the code in this PR: 

Screen Shot 2020-06-06 at 6 02 00 PM

It looks like your proposed changes would increase the difference between the results provided from PyNomaly versus those from the original work. Do you think you would be able to identify the cause of this increased error in the results when compared to the original work?

**Comment by nghiadanh26** [comment]
Hi @vc1492a,
Thanks for looking at my code. I understood your consideration, but now I cannot answer why the differences between PR's results and original results are non-negligible. I'll go deeper inside my code and also LoOP algorithm and I hope I can explain it soon.

**Comment by vc1492a** [comment]
Any updates @nghiadanh26?

**Comment by nghiadanh26** [comment]
Not yet. But I will be soon!

**Comment by vc1492a** [comment]
Any updates @nghiadanh26? I'd close to close this PR soon if there isn't a plan to explore the above, thanks!

**Comment by vc1492a** [comment]
Closing this PR and issue #38 due to inactivity and not resolving the above concern (discrepancy with original paper).

**Pull request closed without merging**
